### ISSUE TITLE
page won't display

### ISSUE THREAD

**Issue by jankeromnes** [espadrine/dev#1]
Hi,
When I run the server and try to access localhost/, the page loads indefinitely and never shows (it remains a blank page). Do you have the same problem?

**Comment by jankeromnes** [comment]
The errors seem to be located in web/js/codeMirror.plug.js (see commit notes for the last commit).
PS : could you rename it to 'codemirror.plug.js' without the capital M?

**Comment by espadrine** [comment]
They were not. A missing line mistake in plugger was the cause.
